export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILED = "FETCH_FAILED";
export const FETCH_DETAILS = "FETCH_DETAILS";
export const DETAILS_LOADING = "DETAILS_LOADING";
export const FETCH_DETAILS_FAILED = "FETCH_DETAILS_FAILED";
